// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? 'AIzaSyCKM-JALo81uLL5mCuyRQV-4TOW6v0kZVg',
    appId: dotenv.env['FIREBASE_APP_ID_WEB'] ?? '1:869997703445:web:c3c87a60aec8dbf9dcf91c',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '869997703445',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'fitnophedia-85e34',
    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'fitnophedia-85e34.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'fitnophedia-85e34.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_MEASUREMENT_ID_WEB'] ?? 'G-DZ9FZ6JFVV',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? 'AIzaSyD0az6IKNIhX7VXsFy2jQR_OsQdoupxnBs',
    appId: dotenv.env['FIREBASE_APP_ID_ANDROID'] ?? '1:869997703445:android:df560e59579e3b63dcf91c',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '869997703445',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'fitnophedia-85e34',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'fitnophedia-85e34.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? 'AIzaSyBlu6h8nw1mWfJHND0FrOm04z98Z0cjqDA',
    appId: dotenv.env['FIREBASE_APP_ID_IOS'] ?? '1:869997703445:ios:5dab79baf3a4ac8fdcf91c',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '869997703445',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'fitnophedia-85e34',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'fitnophedia-85e34.firebasestorage.app',
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.example.fitnophedia',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? 'AIzaSyBlu6h8nw1mWfJHND0FrOm04z98Z0cjqDA',
    appId: dotenv.env['FIREBASE_APP_ID_IOS'] ?? '1:869997703445:ios:5dab79baf3a4ac8fdcf91c',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '869997703445',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'fitnophedia-85e34',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'fitnophedia-85e34.firebasestorage.app',
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.example.fitnophedia',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? 'AIzaSyCKM-JALo81uLL5mCuyRQV-4TOW6v0kZVg',
    appId: dotenv.env['FIREBASE_APP_ID_WEB'] ?? '1:869997703445:web:b0b6d3571e0cfde3dcf91c',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '869997703445',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'fitnophedia-85e34',
    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'fitnophedia-85e34.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'fitnophedia-85e34.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_MEASUREMENT_ID_WINDOWS'] ?? 'G-4TNHP1JXDB',
  );
}
